CREATE TABLE BOARDGAMES
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY,
    NAME      VARCHAR(30)   NOT NULL,
    PUBLISHED INT           NOT NULL,
    RATING    DECIMAL(2, 1) NOT NULL,
    WEIGHT    DECIMAL(2, 1) NOT NULL,
    DURATION  INT           NOT NULL,
    PRICE     DECIMAL(5, 2) NOT NULL,
    PRIMARY KEY (ID)
);